O pacote python-bcb implementa interfaces para algumas APIs disponibilizadas pelo Banco Central de forma que o resultado das consultas, na maioria dos casos, é um DataFrame pandas formatado com os dados.

APIs implementadas: SGS (Sistema Gerenciador de Séries Temporais), Conversor de Moedas, Moedas OData, Expectativas, Taxas de Juros e demais APIs

In [1]:
from bcb import sgs, currency,PTAX,Expectativas,TaxaJuros,ODataAPI

https://www3.bcb.gov.br/sgspub/localizarseries/localizarSeries.do?method=prepararTelaLocalizarSeries

In [2]:
df = sgs.get({'Novo Caged - Total': 28763})

df.head(50)

            Novo Caged - Total
Date
1992-01-01            22378052
1992-02-01            22300499
1992-03-01            22221181
1992-04-01            22158006
1992-05-01            22179539
1992-06-01            22175801
1992-07-01            22147652
1992-08-01            22111414
1992-09-01            22115530
1992-10-01            22067678
1992-11-01            22015913
1992-12-01            21751925
1993-01-01            21785582
1993-02-01            21788513
1993-03-01            21822016
1993-04-01            21849358
1993-05-01            22004159
1993-06-01            22058599
1993-07-01            22075980
1993-08-01            22083895
1993-09-01            22104401
1993-10-01            22113990
1993-11-01            22074455
1993-12-01            21843342
1994-01-01            21876886
1994-02-01            21866075
1994-03-01            21915070
1994-04-01            21987266
1994-05-01            22079979
1994-06-01            22158127
1994-07-01            22167274
1994-08-01            22180122
1994-09-01            22252212
1994-10-01            22309421
1994-11-01            22311798
1994-12-01            22145268
1995-01-01            22134478
1995-02-01            22204152
1995-03-01            22233789
1995-04-01            22321858
1995-05-01            22414061
1995-06-01            22423557
1995-07-01            22359340
1995-08-01            22242484
1995-09-01            22175242
1995-10-01            22131461
1995-11-01            22058257
1995-12-01            22015929
1996-01-01            21953818
1996-02-01            21926329